import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Header } from "@/components/header";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Jenilson Francisco | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt" className={roboto.variable}>
      <body className="bg-zinc-950 text-zinc-50 antialiased">
        <main className="px-5 md:max-w-[1200px] mx-auto">
          <Header />
          {children}
        </main>
      </body>
    </html>
  );
}
