import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import { Header } from "@/components/header";
import "./globals.css";
import { cn } from "@/lib/utils";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Jenilson Francisco | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt"
      className={cn(roboto.variable, "font-sans", "dark antialiased")}
    >
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
